import Foundation

/// Detailed system environment report generated by `DoctorService`.
public struct DoctorReport: Sendable, Equatable {
    public let isCommandLineToolsInstalled: Bool
    public let isConverterAvailable: Bool
    public let developerPath: String?
    public let converterPath: String?

    public nonisolated var isHealthy: Bool {
        isCommandLineToolsInstalled && isConverterAvailable
    }

    public nonisolated init(
        isCommandLineToolsInstalled: Bool,
        isConverterAvailable: Bool,
        developerPath: String? = nil,
        converterPath: String? = nil
    ) {
        self.isCommandLineToolsInstalled = isCommandLineToolsInstalled
        self.isConverterAvailable = isConverterAvailable
        self.developerPath = developerPath
        self.converterPath = converterPath
    }
}

/// Actor responsible for verifying system prerequisites and developer toolchain health.
/// Conforms to Story 1.1 and Architecture requirement FR-12.
public actor DoctorService {
    public static let shared = DoctorService()

    private let processRunner: ProcessRunner

    public init(processRunner: ProcessRunner = .shared) {
        self.processRunner = processRunner
    }

    /// Performs diagnostic checks for Command Line Tools and `safari-web-extension-converter`.
    public func checkPrerequisites() async -> DoctorReport {
        async let cltResult = checkCommandLineTools()
        async let converterResult = checkConverter()

        let (hasCLT, devPath) = await cltResult
        let (hasConverter, convPath) = await converterResult

        return DoctorReport(
            isCommandLineToolsInstalled: hasCLT,
            isConverterAvailable: hasConverter,
            developerPath: devPath,
            converterPath: convPath
        )
    }

    private func checkCommandLineTools() async -> (Bool, String?) {
        do {
            let result = try await processRunner.run(
                command: "/usr/bin/xcode-select",
                arguments: ["-p"]
            )
            if result.isSuccess && !result.standardOutput.isEmpty {
                return (true, result.standardOutput.trimmingCharacters(in: .whitespacesAndNewlines))
            }
        } catch {
            // Failed to run xcode-select
        }
        return (false, nil)
    }

    private func checkConverter() async -> (Bool, String?) {
        do {
            let result = try await processRunner.run(
                command: "/usr/bin/xcrun",
                arguments: ["--find", "safari-web-extension-converter"]
            )
            if result.isSuccess && !result.standardOutput.isEmpty {
                return (true, result.standardOutput.trimmingCharacters(in: .whitespacesAndNewlines))
            }
        } catch {
            // Failed to run xcrun
        }
        return (false, nil)
    }
}
