import Foundation

/// Detailed system environment report generated by `DoctorService`.
public struct DoctorReport: Sendable, Equatable {
    public nonisolated let isCommandLineToolsInstalled: Bool
    public nonisolated let isConverterAvailable: Bool
    public nonisolated let developerPath: String?
    public nonisolated let converterPath: String?

    public nonisolated var isHealthy: Bool {
        isCommandLineToolsInstalled && isConverterAvailable
    }

    public nonisolated var remediationCommand: String {
        "xcode-select --install"
    }

    public nonisolated init(
        isCommandLineToolsInstalled: Bool,
        isConverterAvailable: Bool,
        developerPath: String? = nil,
        converterPath: String? = nil
    ) {
        self.isCommandLineToolsInstalled = isCommandLineToolsInstalled
        self.isConverterAvailable = isConverterAvailable
        self.developerPath = developerPath
        self.converterPath = converterPath
    }
}

/// Actor responsible for verifying system prerequisites and developer toolchain health.
/// Conforms to Story 1.1 and Architecture requirement FR-12.
public actor DoctorService {
    public static let shared = DoctorService()

    private let processRunner: ProcessRunner

    public init(processRunner: ProcessRunner = .shared) {
        self.processRunner = processRunner
    }

    /// Performs diagnostic checks for Command Line Tools and `safari-web-extension-converter`.
    public func checkPrerequisites() async -> DoctorReport {
        async let cltResult = checkCommandLineTools()
        async let converterResult = checkConverter()

        let (hasCLT, devPath) = await cltResult
        let (hasConverter, convPath) = await converterResult

        return DoctorReport(
            isCommandLineToolsInstalled: hasCLT,
            isConverterAvailable: hasConverter,
            developerPath: devPath,
            converterPath: convPath
        )
    }

    private func checkCommandLineTools() async -> (Bool, String?) {
        do {
            let result = try await processRunner.run(
                command: "/usr/bin/xcode-select",
                arguments: ["-p"],
                onOutputLine: nil
            )
            if result.isSuccess {
                let path = result.standardOutput.trimmingCharacters(in: .whitespacesAndNewlines)
                return (!path.isEmpty, path)
            }
            return (false, nil)
        } catch {
            return (false, nil)
        }
    }

    private func checkConverter() async -> (Bool, String?) {
        do {
            let result = try await processRunner.run(
                command: "/usr/bin/xcrun",
                arguments: ["--find", "safari-web-extension-converter"],
                onOutputLine: nil
            )
            if result.isSuccess {
                let path = result.standardOutput.trimmingCharacters(in: .whitespacesAndNewlines)
                return (!path.isEmpty, path)
            }
            return (false, nil)
        } catch {
            return (false, nil)
        }
    }
}
